---
title: "Projects"
---

In the summer of 2020 I took a class GIS course based in R.  This was the second time I've worked with R and I built on some basic knowledge I already had.  The skills I've learned in this class only further proved my point that coding is useful in all fields.  Here's a collection of links from this summer.

## [Building a project website](https://github.com/brynmcgowan22?tab=repositories)

- In this assignment I learned how to get around Rstudio
- Learned different types of formats including Rmarkdown, YMAL, CSS, and HTML
- Wrote code to develop a personalized website
- Created a Github to manage all my projects

## [COVID-19 Pandemic Analysis](https://brynmcgowan22.github.io/geog-176A-labs/lab_02.html)

- In this assignment I learned how to manipulate and visualize real time COVID-19 data
- Learned how to make data frames and join multiple together
- Created tables using knitr and plots using ggplot
- Learned lags and roll means to calculate 7 day averages

## [Projections, Distances, and Mapping](https://brynmcgowan22.github.io/geog-176A-labs/lab_03.html)
- In this assignment I learned about coordinate systems and map projections
- Learned how to build simple feature objects
- Learned how to calculate the distance to various borders from US cities and how to map it

## [Tesselations, Spatial Joins, and Point-in-Polygon](https://brynmcgowan22.github.io/geog-176A-labs/lab_04.html)
- In this assignment I used different types of tessellations to analyze US dam data
- Used functions to simplify and speed up mapping process
- Created point-in-polygon counts to visualize dam distribution across the US

## [Raster Analysis](https://brynmcgowan22.github.io/geog-176A-labs/lab_05.html)
- In this assignment we used raster files to analyze flood data in Palo, Iowa
- Used different RGB combinations to manipulate landsat imagery
- Used threshold functions to find surface water
- Learned about kmeans rasters

## [Terrain Analysis](https://brynmcgowan22.github.io/geog-176A-labs/lab_06.html)
- In this assignment I analyzed flood impacts near Mission Creek using USGS water data
- Created a hillshade raster to visualize the flood impacts and a HAND raster for rapid flood assessment
- Created a map to visualize buildings impacted by the flood
